- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker and Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes